workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "center.usahome.app"
      node: v18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: npm ci
      - name: Configure iOS dependencies
        script: |
          cd ios/App
          pod install --repo-update
      - name: Create optimized web build
        script: |
          mkdir -p client/dist
          cat > client/dist/index.html << 'HTML'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
            <meta name="apple-mobile-web-app-capable" content="yes">
            <meta name="apple-mobile-web-app-status-bar-style" content="default">
            <title>USA Home</title>
            <style>
              * { margin: 0; padding: 0; box-sizing: border-box; }
              body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                background: linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%);
                color: white;
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
                padding: 20px;
              }
              .container { 
                text-align: center;
                background: rgba(255, 255, 255, 0.1);
                padding: 50px 30px;
                border-radius: 20px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
                max-width: 350px;
                width: 100%;
              }
              h1 { 
                font-size: 2.5rem; 
                font-weight: 700;
                margin-bottom: 20px;
                letter-spacing: -1px;
              }
              .tagline { 
                font-size: 1.1rem; 
                margin-bottom: 15px;
                opacity: 0.9;
                font-weight: 500;
              }
              .description { 
                font-size: 0.95rem; 
                margin-bottom: 25px;
                opacity: 0.8;
                line-height: 1.4;
              }
              .version { 
                font-size: 0.85rem; 
                opacity: 0.7;
                background: rgba(255, 255, 255, 0.1);
                padding: 8px 16px;
                border-radius: 12px;
                display: inline-block;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>USA Home</h1>
              <p class="tagline">Home Building & Design</p>
              <p class="description">Connecting homeowners with professionals across America</p>
              <div class="version">iOS Version 1.0</div>
            </div>
          </body>
          </html>
          HTML
          
          echo '{"name":"USA Home","short_name":"USA Home","start_url":"/","display":"standalone","background_color":"#1e3a8a","theme_color":"#3b82f6"}' > client/dist/manifest.json
          
          npx cap sync ios
      - name: Setup build environment
        script: keychain initialize
      - name: Build iOS archive
        script: |
          cd ios/App
          
          xcodebuild clean \
            -workspace App.xcworkspace \
            -scheme App
          
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            PROVISIONING_PROFILE="" \
            DEVELOPMENT_TEAM="" \
            -allowProvisioningUpdates
    artifacts:
      - ios/App/build/App.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - shirinhamidi@gmail.com
        notify:
          success: true
          failure: false
