workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "center.usahome.app"
      node: v18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Create build in correct location
        script: |
          mkdir -p client/dist
          mkdir -p client/dist/assets
          cat > client/dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
            <title>USA Home</title>
            <style>
              * { margin: 0; padding: 0; box-sizing: border-box; }
              body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
              }
              .container { 
                text-align: center; 
                padding: 40px 20px;
                background: rgba(255, 255, 255, 0.1);
                border-radius: 20px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
              }
              h1 { 
                font-size: 2.5rem; 
                margin-bottom: 20px; 
                font-weight: 700;
              }
              p { 
                font-size: 1.1rem; 
                margin-bottom: 10px; 
                opacity: 0.9;
              }
              .version { 
                font-size: 0.9rem; 
                opacity: 0.7; 
                margin-top: 20px;
              }
            </style>
          </head>
          <body>
            <div id="root">
              <div class="container">
                <h1>USA Home</h1>
                <p>Home Building, Design & Finance Platform</p>
                <p>Connecting homeowners with professionals</p>
                <div class="version">Version 1.0 - iOS App</div>
              </div>
            </div>
          </body>
          </html>
          EOF
          
          cat > client/dist/manifest.json << 'EOF'
          {
            "name": "USA Home",
            "short_name": "USA Home",
            "start_url": "/",
            "display": "standalone",
            "background_color": "#667eea",
            "theme_color": "#764ba2",
            "icons": []
          }
          EOF
          
          ls -la client/dist/
      - name: Capacitor sync
        script: |
          npx cap sync ios --verbose
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
