workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "center.usahome.app"
      node: v18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Setup iOS dependencies
        script: |
          cd ios/App
          pod install --repo-update
      - name: Prepare web assets
        script: |
          ls -la client/dist/
          npx cap sync ios
      - name: Setup keychain
        script: keychain initialize
      - name: Build iOS archive
        script: |
          cd ios/App
          xcodebuild clean -workspace App.xcworkspace -scheme App
          xcodebuild archive -workspace App.xcworkspace -scheme App -configuration Release -destination generic/platform=iOS -archivePath build/App.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/App.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - shirinhamidi@gmail.com
        notify:
          success: true
          failure: false
