workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "center.usahome.app"
      node: v18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Setup iOS
        script: |
          cd ios/App
          pod install --repo-update
      - name: Create simple web content
        script: |
          mkdir -p client/dist
          echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>USA Home</title><style>body{margin:0;font-family:system-ui;background:#1e3a8a;color:white;display:flex;align-items:center;justify-content:center;min-height:100vh;padding:20px}.app{text-align:center;background:rgba(255,255,255,0.1);padding:40px;border-radius:20px;backdrop-filter:blur(10px)}h1{font-size:2.5rem;margin-bottom:20px}p{font-size:1.1rem;margin:10px 0;opacity:0.9}</style></head><body><div class="app"><h1>USA Home</h1><p>Home Building & Design Platform</p><p>iOS Version 1.0</p></div></body></html>' > client/dist/index.html
          echo '{"name":"USA Home","short_name":"USA Home","start_url":"/","display":"standalone"}' > client/dist/manifest.json
          npx cap sync ios
      - name: Initialize keychain
        script: keychain initialize
      - name: Build archive
        script: |
          cd ios/App
          xcodebuild clean -workspace App.xcworkspace -scheme App
          xcodebuild archive -workspace App.xcworkspace -scheme App -configuration Release -destination generic/platform=iOS -archivePath build/App.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/App.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - shirinhamidi@gmail.com
        notify:
          success: true
          failure: false
