import { createContext, ReactNode, useContext, useState, useEffect } from "react";
import { languageOptions } from "@/data/languageData";

// Define the type for our context
type LanguageContextType = {
  currentLanguage: typeof languageOptions[0];
  setLanguage: (language: typeof languageOptions[0]) => void;
  t: (key: string) => string;
};

// Create the context with null as initial value
export const LanguageContext = createContext<LanguageContextType | null>(null);

// Default language is English
const defaultLanguage = languageOptions[0]; 

// Language Provider Component
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState(defaultLanguage);
  
  // Load saved language from localStorage if available
  useEffect(() => {
    const savedLanguageCode = localStorage.getItem('languageCode');
    if (savedLanguageCode) {
      const savedLanguage = languageOptions.find(lang => lang.code === savedLanguageCode);
      if (savedLanguage) {
        setCurrentLanguage(savedLanguage);
      }
    }
    
    // Also update the HTML lang attribute
    document.documentElement.lang = currentLanguage.code;
    document.documentElement.dir = currentLanguage.code === 'ar' || currentLanguage.code === 'fa' ? 'rtl' : 'ltr';
  }, [currentLanguage.code]);
  
  // Function to change the language
  const handleSetLanguage = (language: typeof languageOptions[0]) => {
    // Update the current language state
    setCurrentLanguage(language);
    
    // Save to localStorage for persistence
    localStorage.setItem('languageCode', language.code);
    
    // Log for debugging
    console.log(`Language changed to ${language.name} (${language.code})`);
    console.log(`Translations available:`, Object.keys(translations));
    console.log(`Translation keys for ${language.code}:`, 
      translations[language.code] ? Object.keys(translations[language.code]).length : 'none');
    console.log(`Sample translation for "home" in ${language.code}:`, 
      translations[language.code]?.home || 'not found');
    
    // Update the HTML lang attribute
    document.documentElement.lang = language.code;
    document.documentElement.dir = language.code === 'ar' || language.code === 'fa' ? 'rtl' : 'ltr';
  };
  
  // Translation function
  const t = (key: string): string => {
    // Debug - log current language and key
    console.log(`Translating key "${key}" for language "${currentLanguage.code}"`);
    
    // If translation exists for current language, return it
    if (translations[currentLanguage.code] && translations[currentLanguage.code][key]) {
      const translated = translations[currentLanguage.code][key];
      console.log(`Found translation: "${translated}"`);
      return translated;
    }
    
    // Fallback to English
    if (translations.en && translations.en[key]) {
      const fallback = translations.en[key];
      console.log(`Fallback to English: "${fallback}"`);
      return fallback;
    }
    
    // If no translation is found, return the key itself
    console.log(`No translation found for key: "${key}"`);
    return key;
  };

  return (
    <LanguageContext.Provider value={{ 
      currentLanguage, 
      setLanguage: handleSetLanguage, 
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Hook to use language context
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Helper function to use translations outside of React components
export function useTranslate() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useTranslate must be used within a LanguageProvider");
  }
  return context.t;
}

// Simple translation system - export all translations
export const translations: Record<string, Record<string, string>> = {
  en: {
    // Already listed professional UI
    "already_listed": "Already Listed",
    "already_listed_message_1": "You are already listed as a",
    "already_listed_message_2": "professional. You can manage your profile from your account page.",
    "go_to_my_account": "Go to My Account",
    "back_to_services": "Back to Services",
    
    // Service category management
    "service_categories": "Service Categories",
    "add_service_category": "Add New Service",
    "select_new_service": "Select New Service Category",
    "current_categories": "Current Categories",
    "service_added_successfully": "Service Added Successfully",
    "your_profile_now_appears_in": "Your profile now appears in the",
    "category": "category",
    "additional_service_added": "Your additional service has been added successfully",
    "clients_can_find_you_all_categories": "Clients can now find you in all your listed service categories",
    "return_to_home": "Return to Home",
    
    // Finance page counts
    "professional_types_count": "{count} professional types including {services}, and more.",
    
    // Navigation and error handling
    "back_to_finance": "Back to Finance & Real Estate",
    "category_not_found_description": "We couldn't find the category you were looking for. Please go back and try again.",
    
    // Professional profile fields
    "professional_details": "Professional Details",
    "edit_professional_details": "Edit Professional Details",
    "years_of_experience": "Years of Experience",
    "certifications": "Certifications & Qualifications",
    "certifications_placeholder": "e.g., Licensed Contractor, LEED Certified, Master Plumber",
    "separate_certifications_with_commas": "Separate multiple certifications with commas",
    "service_areas": "Service Areas",
    "service_areas_placeholder": "e.g., Downtown, North Side, All of Metro Area",
    "enter_cities_neighborhoods": "Enter cities, neighborhoods, or regions you serve",
    "business_description": "Business Description",
    "business_description_placeholder": "Describe your services, expertise, and what makes your business unique...",
    "character_count": "{count} characters",
    "saving": "Saving...",
    "profile_save_changes": "Save Changes",
    "profile_cancel": "Cancel",
    "about": "About This Professional",
    "profile_experience": "Experience",
    "states_serviced": "States Serviced",
    "languages": "Languages Spoken",
    "not_specified": "Not Specified",
    "phone": "Phone",
    "social_media": "Social Media",
    "edit_profile": "Edit Profile",
    "contact_information": "Contact Information",
    "none_added": "None Added",
    "languages_spoken": "Languages Spoken",
    
    // Profile image upload
    "change_profile_picture": "Change Profile Picture",
    "change_picture": "Change Picture",
    "uploading": "Uploading...",
    
    // Professional response form
    "respond_to_reviews": "Respond to Reviews",
    "respond_to_this_review": "Respond to this review",
    "respond": "Respond",
    "edit_button": "Edit",
    "delete_button": "Delete",
    "edit_response": "Edit Response",
    "delete_response": "Delete Response",
    "edit_your_response": "Edit your response",
    "cancel_button": "Cancel",
    "save_response": "Save Changes",
    "confirm_delete": "Confirm Delete",
    "delete_response_confirm": "Are you sure you want to delete your response?",
    "response_deleted": "Response Deleted",
    "response_edited": "Response Edited",
    "your_response_has_been_deleted": "Your response has been deleted successfully!",
    "your_response_has_been_edited": "Your response has been edited successfully!",
    "as_a_professional_response_info": "As the business owner, you can respond to customer reviews to address feedback publicly.",
    "type_your_response": "Type your response to customer reviews here...",
    "response_required": "Response text is required",
    "sending": "Sending...",
    "send_response": "Send Response",
    "professional_response_guidelines": "Be professional and courteous in your responses. Address concerns and thank customers for their feedback.",
    "professional_response": "Professional Response",
    "response_submitted": "Response Submitted",
    "your_response_has_been_added": "Your response has been added successfully!",
    "error": "Error",
    "something_went_wrong": "Something went wrong. Please try again.",
    "authentication_required": "Authentication Required",
    "please_login": "Please log in to continue.",
    "cannot_review_professional": "You cannot review this professional at this time.",
    "can_review_as_guest": "You can still leave a review as a guest:",
    "how_was_your_experience": "How was your experience?",
    "share_your_experience": "Share Your Experience",
    "your_review": "Your Review",
    "share_experience_placeholder": "Share your experience with this professional...",
    "review_min_length": "Review must be at least 10 characters",
    "provide_feedback": "Please provide your feedback",
    "submitting": "Submitting...",
    "submit_review": "Submit Review",
    "love_it": "Love it",
    "like_it": "Like it",
    "neutral": "Neutral",
    "dislike": "Dislike",
    "terrible": "Terrible",
    "review_submitted": "Review Submitted",
    "thank_you_for_feedback": "Thank you for your feedback!",
    "review_submission_failed": "Failed to Submit Review",
    "checking_review_eligibility": "Checking review eligibility...",
    "profile_picture_updated": "Profile Picture Updated",
    "profile_picture_update_success": "Your profile picture has been updated successfully",
    "profile_picture_update_failed": "Failed to Update Profile Picture",
    "invalid_file_type": "Invalid File Type",
    "please_upload_image": "Please upload an image file (JPEG, PNG, etc.)",
    "file_too_large": "File Too Large",
    "max_file_size_5mb": "Maximum file size is 5MB",
    "years_experience_count": "{count} years in business",
    "complete_your_profile": "Complete your professional profile to attract more clients",
    "add_professional_details": "Add Professional Details",
    "profile_updated": "Profile Updated",
    "profile_update_success": "Your professional profile has been updated successfully",
    "profile_update_failed": "Profile Update Failed",
    "edit_profile_button": "Edit",
    "no_states_selected": "No states selected",
    "add_state": "Add State",
    "states_multiselect_hint": "Select states from the dropdown to add them to your service area. Click the × to remove states.",
    
    // Common UI elements
    "home": "Home",
    "my_profile": "My Profile",
    "support": "Support",
    "services": "Services",
    "contact": "Contact",
    "back": "Back",
    "next": "Next",
    "yes": "Yes",
    "no": "No",
    "continue": "Continue",
    "previous": "Previous",
    "submit": "Submit",
    "cancel": "Cancel",
    "login": "Login",
    "logout": "Logout",
    "register": "Register",
    "email": "Email",
    "password": "Password",
    "confirm_password": "Confirm Password",
    "forgot_password": "Forgot Password?",
    "reset_password": "Reset Password",
    "login_successful": "Login Successful",
    "welcome_back": "Welcome back, {username}!",
    "login_failed": "Login Failed",
    "registration_successful": "Registration Successful",
    "welcome_new_user": "Welcome, {username}!",
    "registration_failed": "Registration Failed",
    "logged_out": "Logged Out",
    "logout_success_message": "You have been successfully logged out.",
    "logout_failed": "Logout Failed",
    "my_account": "My Account",
    "payment_info": "Payment Information",
    "update_payment": "Update Payment Info",
    "subscription_inactive_title": "Subscription Inactive",
    "subscription_inactive_login_message": "Your professional subscription has expired. Reactivate now to ensure potential clients can contact you and see your full profile.",
    "activate_account": "Activate Account",
    "dismiss": "Dismiss",
    "save_preferences": "Save Preferences",
    "configure": "Configure",
    "active": "Active",
    "code": "Code",
    
    // Navigation
    "build_home": "Build Home",
    "design_home": "Design Home",
    "finance_real_estate": "Finance & Real Estate",
    
    // Home page
    "welcome_message": "Welcome to USA Home",
    "welcome_subtitle": "Your gateway to professional home services",
    "find_professionals": "Find professionals for your home project",
    "are_you_a_pro": "Are you a professional service provider?",
    "list_your_services": "List your services",
    "your_dream_home": "Your Dream Home",
    "starts_here": "Starts Here",
    "transform_vision": "Transform your vision into reality with USA Home - your comprehensive platform for building, designing, and financing your perfect home.",
    "comprehensive_platform": "Your comprehensive platform for home building, design, and financing solutions.",
    "quick_links": "Quick Links",
    "about_us": "About Us",
    "service_menu": "Services",
    "contact_us": "Contact",
    "home_building": "Home Building",
    "home_design": "Home Design",
    "financing": "Financing",
    "real_estate": "Real Estate",
    "connect_with_us": "Connect With Us",
    "subscribe_newsletter": "Subscribe to our newsletter for updates",
    "your_email": "Your email",
    "subscribe": "Subscribe",
    "house_illustration_title": "USA Home - American Design for American Homes",
    "click_to_explore": "Click on the house elements to explore our services",
    "modern_home_solutions": "Modern American Home Solutions",
    "design_your_dream_home": "Design Your Dream Home",
    "connect_with_design_professionals": "Connect with top design and planning professionals to bring your vision to life.",
    "search_design_services": "Search design services (e.g., 'arch' for architect, 'int' for interior)",
    "no_design_services_found": "No design services found matching your search. Try a different term.",
    "back_to_home": "Back to Home",
    "build": "Build",
    "find_pros": "Find pros",
    "design": "Design",
    "interior": "Interior",
    "finance": "Finance",
    "real_estate_short": "Real estate",
    
    // Professional pages
    "service_area": "Service Area",
    "service_location": "Service Location",
    "license_info": "License Information",
    "experience": "Experience",
    "select_languages": "Select Languages",
    "upload_documents": "Upload Documents",
    "payment_details": "Payment Details",
    "professional_finder": "Professional Finder",
    "professional_directory": "Professional Directory",
    "are_you_professional": "Are you a professional service provider?",
    "professional_question_desc": "Please select whether you are looking for service providers or are a professional offering services",
    "looking_for_professionals": "I'm looking for professionals",
    "i_am_professional": "I am a professional",
    "want_to_be_listed": "Do you want to be listed among your field's professionals?",
    "get_discovered": "Get discovered by homeowners looking for",
    "professionals": "professionals",
    "premium_listings": "Premium listings include priority placement and direct contact options.",
    "professional_listing_price": "Professional Listing - $29.77 per month",
    "free_trial_info": "Start with a 30-day free trial! No charge until trial ends.",
    "want_to_be_listed_yes": "I want to be listed in the directory",
    "for": "for",
    "want_to_browse": "I just want to browse the directory",
    "for_professionals": "for professionals",
    "continue_without_listing": "Continue without listing",
    
    // Build Home page
    "search_services_placeholder": "Search services (e.g., 'plum' for plumber, 'elec' for electrician)",
    "view_services": "View Services",
    "category_not_found": "Category Not Found",
    "back_to_categories": "Back to Categories",
    "no_finance_professionals_found": "No finance professionals found matching your search criteria.",
    "view_options": "View Options",
    "learn_more": "Learn More",
    "coming_soon": "Coming soon! We're working on detailed information for this category.",
    
    // Category names
    "construction_building": "Construction & Building",
    "construction_building_desc": "Comprehensive construction services for your home building project.",
    "mep": "MEP (Mechanical, Electrical, Plumbing)",
    "mep_desc": "Essential MEP systems for a functional and comfortable home.",
    "utilities_infrastructure": "Utilities & Infrastructure",
    "utilities_infrastructure_desc": "Connecting essential utilities to your home for daily living.",
    "renewable_solar": "Renewable & Solar",
    "renewable_solar_desc": "Sustainable energy solutions for modern, efficient homes.",
    "energy_building_systems": "Energy & Building Systems",
    "energy_building_systems_desc": "Smart and efficient building systems for modern living.",
    "environmental_compliance": "Environmental & Compliance",
    "environmental_compliance_desc": "Ensuring your home meets environmental standards and regulations.",
    "additional_expertise": "Additional Expertise",
    "additional_expertise_desc": "Specialized services for specific home building needs.",
    
    // Finance pages
    "mortgage": "Mortgage",
    "insurance": "Insurance",
    "credit_repair": "Credit Repair",
    "financial_planning": "Financial Planning", 
    "real_estate_agents": "Real Estate Agents",
    "loan_officers": "Loan Officers",
    "find_finance_professionals": "Find Finance & Real Estate Professionals",
    "search_finance_professionals": "Search finance professionals...",
    "find_connect_finance_professionals": "Find and connect with top professionals in finance and real estate",
    "connect_with_category": "Connect with trusted specialists in this category",
    
    // Finance categories
    "credit_repair_debt_management": "Credit Repair & Debt Management",
    "mortgage_loan_professionals": "Mortgage & Loan Professionals",
    "construction_finance_experts": "Construction Finance Experts",
    "home_improvement_financing": "Home Improvement Financing",
    "equity_refinance_debt": "Equity, Refinance & Debt",
    "first_time_buyer_credit": "First-Time Buyer Credit",
    "real_estate_investment_experts": "Real Estate Investment Experts",
    "real_estate_property_professionals": "Real Estate Property Professionals",
    "financial_planning_tax_experts": "Financial Planning & Tax Experts",
    
    // Language
    "language": "Language",
    "language_selection": "Language Selection",
    "select_language": "Select Language",
    "english": "English",
    "spanish": "Spanish",
    "persian": "Persian",
    "arabic": "Arabic",
    "chinese": "Chinese",
    "hindi": "Hindi",
    "filipino": "Filipino",
    "korean": "Korean",
    "current_language": "Current Language",
    "switch_language": "Switch Language",
    "language_support": "Language Support",
    "language_support_desc": "We provide support in multiple languages to make finding professionals easier.",
    "translation": "Translation",
    "translate": "Translate",
    "translator": "Translator",
    "translator_service": "Translator Service",
    "translation_service": "Translation Service",
    "language_settings": "Language Settings",
    "language_preference": "Language Preference",
    "multilingual": "Multilingual",
    "multilingual_support": "Multilingual Support",
    "translation_incomplete": "Translation incomplete. Some content may display in English.",
    "translation_in_progress": "Translation in progress...",
    "help_translate": "Help Translate",
    "contribute_translations": "Contribute Translations",
    "translation_contributors": "Translation Contributors",
    "translation_team": "Translation Team",
    "translators": "Translators",
    "translation_community": "Translation Community",
    "translation_project": "Translation Project", 
    "translation_guide": "Translation Guide",
    "translation_standards": "Translation Standards",
    "translation_quality": "Translation Quality",
    "translation_review": "Translation Review",
    "translation_glossary": "Translation Glossary",
    "translation_terms": "Translation Terms",
    "translation_feedback": "Translation Feedback",
    "report_translation_error": "Report Translation Error",
    "submit_translation": "Submit Translation",
    "approve_translation": "Approve Translation",
    "reject_translation": "Reject Translation",
    "translation_status": "Translation Status",
    "translation_progress": "Translation Progress",
    "translation_complete": "Translation Complete",
    "translation_pending": "Translation Pending",
    "translation_approved": "Translation Approved",
    "translation_rejected": "Translation Rejected",
    "translation_statistics": "Translation Statistics",
    "translation_metrics": "Translation Metrics",
    "translation_history": "Translation History",
    "translation_version": "Translation Version",
    "translation_changes": "Translation Changes",
    "translation_updates": "Translation Updates",
    "translation_manager": "Translation Manager",
    "translation_coordinator": "Translation Coordinator",
    "language_coordinator": "Language Coordinator",
    "localization": "Localization",
    "localization_team": "Localization Team",
    "localization_manager": "Localization Manager",
    "localization_coordinator": "Localization Coordinator",
    "localization_project": "Localization Project",
    "localization_guide": "Localization Guide",
    "localization_standards": "Localization Standards",
    "localization_quality": "Localization Quality",
    "localization_review": "Localization Review",
    "localization_glossary": "Localization Glossary",
    "localization_terms": "Localization Terms",
    "localization_feedback": "Localization Feedback",
    "report_localization_error": "Report Localization Error", 
    "submit_localization": "Submit Localization",
    "approve_localization": "Approve Localization",
    "reject_localization": "Reject Localization",
    "localization_status": "Localization Status",
    "localization_progress": "Localization Progress",
    "localization_complete": "Localization Complete",
    "localization_pending": "Localization Pending",
    "localization_approved": "Localization Approved",
    "localization_rejected": "Localization Rejected",
    "localization_statistics": "Localization Statistics",
    "localization_metrics": "Localization Metrics",
    "localization_history": "Localization History",
    "localization_version": "Localization Version",
    "localization_changes": "Localization Changes",
    "localization_updates": "Localization Updates",
    "internationalization": "Internationalization",
    "i18n": "i18n",
    "l10n": "l10n",
    "g11n": "g11n",
    "contributors": "Contributors",
    "active_translation_contributors": "Active Translation Contributors"
  },
  es: {
    // Already listed professional UI
    "already_listed": "Ya Registrado",
    "already_listed_message_1": "Ya estás registrado como profesional de",
    "already_listed_message_2": ". Puedes administrar tu perfil desde tu página de cuenta.",
    "go_to_my_account": "Ir a Mi Cuenta",
    "back_to_services": "Volver a Servicios",
    
    // Service category management
    "service_categories": "Categorías de Servicio",
    "add_service_category": "Añadir Nuevo Servicio",
    "select_new_service": "Seleccionar Nueva Categoría de Servicio",
    "current_categories": "Categorías Actuales",
    "service_added_successfully": "Servicio Añadido Exitosamente",
    "your_profile_now_appears_in": "Tu perfil ahora aparece en la categoría",
    "category": "categoría",
    "additional_service_added": "Tu servicio adicional ha sido añadido exitosamente",
    "clients_can_find_you_all_categories": "Los clientes ahora pueden encontrarte en todas tus categorías de servicio listadas",
    "return_to_home": "Volver al Inicio",
    
    "connect_with_category": "Conéctate con especialistas de confianza en esta categoría",
    "back": "Atrás",
    "category_not_found": "Categoría No Encontrada",
    "design_home": "Diseño de Casa",
    "build_home": "Construir Casa",
    "finance_real_estate": "Finanzas y Bienes Raíces",
    "design": "Diseño",
    "build": "Construir",
    "finance": "Finanzas",
    "real_estate_short": "Bienes raíces",
    "looking_for_professionals": "Busco profesionales",
    "i_am_professional": "Soy un profesional",
    "home": "Inicio",
    "support": "Soporte",
    "services": "Servicios",
    "contact": "Contacto",
    "login": "Iniciar sesión",
    "my_profile": "Mi Perfil",
    "my_account": "Mi Cuenta",
    "next": "Siguiente",
    "previous": "Anterior",
    "submit": "Enviar",
    "cancel": "Cancelar",
    "logout": "Cerrar sesión",
    "register": "Registrarse",
    "email": "Correo electrónico",
    "password": "Contraseña",
    "construction_building": "Construcción y Edificación",
    "mep": "MEP (Mecánica, Eléctrica, Plomería)",
    "utilities_infrastructure": "Servicios e Infraestructura",
    "renewable_solar": "Energía Renovable y Solar",
    "energy_building_systems": "Sistemas de Energía y Edificación",
    "environmental_compliance": "Medio Ambiente y Cumplimiento",
    "additional_expertise": "Experiencia Adicional"
  },
  fa: {
    "connect_with_category": "با متخصصان معتبر در این دسته ارتباط برقرار کنید",
    "back": "بازگشت",
    "category_not_found": "دسته‌بندی یافت نشد",
    "design_home": "طراحی خانه",
    "build_home": "ساخت خانه",
    "finance_real_estate": "امور مالی و املاک",
    "design": "طراحی",
    "build": "ساخت",
    "finance": "امور مالی",
    "real_estate_short": "املاک",
    "looking_for_professionals": "به دنبال متخصصان هستم",
    "i_am_professional": "من یک متخصص هستم",
    "home": "خانه",
    "support": "پشتیبانی",
    "services": "خدمات",
    "contact": "تماس",
    "login": "ورود",
    "my_profile": "پروفایل من",
    "my_account": "حساب من",
    "next": "بعدی",
    "previous": "قبلی",
    "submit": "ارسال",
    "cancel": "لغو",
    "logout": "خروج",
    "register": "ثبت نام",
    "email": "ایمیل",
    "password": "رمز عبور",
    "construction_building": "ساخت و ساز",
    "mep": "MEP (مکانیک، برق، لوله‌کشی)",
    "utilities_infrastructure": "خدمات و زیرساخت",
    "renewable_solar": "انرژی تجدیدپذیر و خورشیدی",
    "energy_building_systems": "سیستم‌های انرژی و ساختمان",
    "environmental_compliance": "محیط زیست و تطابق",
    "additional_expertise": "تخصص‌های اضافی"
  },
  ar: {

    "back": "رجوع",
    "category_not_found": "الفئة غير موجودة",
    "design_home": "تصميم المنزل",
    "build_home": "بناء المنزل",
    "finance_real_estate": "التمويل والعقارات",
    "design": "تصميم",
    "build": "بناء",
    "finance": "تمويل",
    "real_estate_short": "عقارات",
    "category": "الفئة",
    "looking_for_professionals": "أبحث عن محترفين",
    "i_am_professional": "أنا محترف",
    "home": "الرئيسية",
    "support": "الدعم",
    "services": "الخدمات",
    "contact": "اتصل بنا",
    "login": "تسجيل الدخول",
    "my_profile": "ملفي الشخصي",
    "my_account": "حسابي",
    "next": "التالي",
    "previous": "السابق",
    "submit": "إرسال",
    "cancel": "إلغاء",
    "logout": "تسجيل الخروج",
    "register": "تسجيل",
    "email": "البريد الإلكتروني",
    "password": "كلمة المرور",
    "your_dream_home": "منزل أحلامك",
    "starts_here": "يبدأ هنا",
    "transform_vision": "حول رؤيتك إلى واقع مع USA Home - منصتك الشاملة لبناء وتصميم وتمويل منزلك المثالي.",
    "comprehensive_platform": "منصتك الشاملة لحلول بناء المنازل والتصميم والتمويل.",
    "quick_links": "روابط سريعة",
    "about_us": "من نحن",
    "service_menu": "الخدمات",
    "contact_us": "اتصل بنا",
    "home_building": "بناء المنزل",
    "home_design": "تصميم المنزل",
    "financing": "التمويل",
    "real_estate": "العقارات",
    "connect_with_us": "تواصل معنا",
    "subscribe_newsletter": "اشترك في نشرتنا الإخبارية للحصول على التحديثات",
    "your_email": "بريدك الإلكتروني",
    "subscribe": "اشتراك",
    "forgot_password": "نسيت كلمة المرور؟",
    
    // Design Home page
    "design_your_dream_home": "صمم منزل أحلامك",
    "connect_with_design_professionals": "تواصل مع أفضل محترفي التصميم والتخطيط لتحقيق رؤيتك",
    "search_design_services": "ابحث عن خدمات التصميم (مثال، 'arch' للمعماري، 'int' للتصميم الداخلي)",
    "no_design_services_found": "لم يتم العثور على خدمات تصميم تطابق بحثك. جرب مصطلحا مختلفا.",
    "back_to_home": "العودة إلى الصفحة الرئيسية",
    
    // Design Home subcategories
    "design_architect": "المهندس المعماري",
    "design_architect_desc": "خدمات معمارية احترافية لإنشاء تصميم منزل أحلامك.",
    "design_structural_engineer": "مهندس الإنشاءات",
    "design_structural_engineer_desc": "خبرة هندسية لضمان سلامة منزلك الهيكلية والسلامة.",
    "design_civil_engineer": "المهندس المدني",
    "design_civil_engineer_desc": "تطوير الموقع وتخطيط البنية التحتية لممتلكاتك.",
    "design_urban_planner": "مخطط المدن",
    "design_urban_planner_desc": "التنقل في قوانين تقسيم المناطق ومتطلبات التطوير الحضري.",
    "design_interior_designer": "مصمم داخلي",
    "design_interior_designer_desc": "إنشاء مساحات داخلية جميلة وعملية لمنزلك.",
    "design_landscape_architect": "مهندس المناظر الطبيعية",
    "design_landscape_architect_desc": "تصميم المساحات الخارجية التي تكمل منزلك وأسلوب حياتك.",
    "design_sustainability_consultant": "مستشار الاستدامة",
    "design_sustainability_consultant_desc": "إرشادات خبيرة لإنشاء منزل صديق للبيئة وموفر للطاقة.",
    
    // Design Home third-level items - Architect
    "concept_development": "تطوير المفهوم",
    "concept_development_desc": "المفاهيم والأفكار التصميمية الأولية لمشروع منزلك.",
    "schematic_design": "التصميم التخطيطي",
    "schematic_design_desc": "رسومات ورسومات أولية لتحديد اتجاه المشروع.",
    "design_development": "تطوير التصميم",
    "design_development_desc": "تنقيح وتفصيل التصميم التخطيطي المعتمد.",
    "construction_documentation": "وثائق البناء",
    "construction_documentation_desc": "رسومات ومواصفات مفصلة لأغراض البناء.",
    "3d_modeling_&_visualization": "النمذجة والتصور ثلاثي الأبعاد",
    "3d_modeling_&_visualization_desc": "إنشاء نماذج وعروض ثلاثية الأبعاد واقعية لمنزلك المستقبلي.",
    
    // Design Home third-level items - Structural Engineer
    "structural_analysis": "التحليل الهيكلي",
    "structural_analysis_desc": "تقييم السلوك الهيكلي واستقرار تصاميم المباني.",
    "material_selection": "اختيار المواد",
    "material_selection_desc": "اختيار المواد الهيكلية المثلى لمتطلبات مشروعك.",
    "foundation_design": "تصميم الأساسات",
    "foundation_design_desc": "هندسة أساسات آمنة ومستقرة لمبناك.",
    "seismic_&_wind_analysis": "تحليل الزلازل والرياح",
    "seismic_&_wind_analysis_desc": "ضمان قدرة الهياكل على تحمل القوى البيئية والكوارث الطبيعية.",
    "reinforcement_detailing": "تفاصيل التسليح",
    "reinforcement_detailing_desc": "تحديد متطلبات التسليح للخرسانة وغيرها من العناصر الهيكلية.",
    
    // Design Home third-level items - Civil Engineer
    "site_development": "تطوير الموقع",
    "site_development_desc": "تخطيط وتجهيز أرضك للبناء.",
    "drainage_&_water_management": "تصريف المياه وإدارتها",
    "drainage_&_water_management_desc": "تصميم أنظمة للتحكم في تدفق المياه ومنع الفيضانات.",
    "road_&_infrastructure_design": "تصميم الطرق والبنية التحتية",
    "road_&_infrastructure_design_desc": "تخطيط طرق الوصول والبنية التحتية ذات الصلة لممتلكاتك.",
    "geotechnical_engineering": "هندسة تقنية الأرض",
    "geotechnical_engineering_desc": "تحليل ميكانيكا التربة والصخور لدعم تصميم الأساسات.",
    "utility_planning": "تخطيط المرافق",
    "utility_planning_desc": "تنسيق دمج الكهرباء والمياه والمرافق الأخرى.",
    
    // Design Home third-level items - Urban Planner
    "land_use_planning": "تخطيط استخدام الأراضي",
    "land_use_planning_desc": "التخطيط الاستراتيجي للاستخدام الأمثل للممتلكات.",
    "zoning_regulations_&_compliance": "لوائح تقسيم المناطق والامتثال",
    "zoning_regulations_&_compliance_desc": "ضمان تلبية مشروعك لجميع متطلبات التقسيم المحلية.",
    "community_development_plans": "خطط تنمية المجتمع",
    "community_development_plans_desc": "دمج مشروعك مع أهداف تنمية المجتمع الأوسع.",
    "transportation_planning": "تخطيط النقل",
    "transportation_planning_desc": "التخطيط للوصول والبنية التحتية للنقل لمشروعك.",
    "environmental_impact_assessments": "تقييمات الأثر البيئي",
    "environmental_impact_assessments_desc": "تقييم الآثار البيئية لتطويرك.",
    
    // Design Home third-level items - Interior Designer
    "space_planning": "تخطيط المساحة",
    "space_planning_desc": "تحسين تخطيطات الغرف وتدفق الحركة للراحة والوظائف.",
    "furniture_&_fixtures_selection": "اختيار الأثاث والتركيبات",
    "furniture_&_fixtures_selection_desc": "اختيار الأثاث والتركيبات المناسبة لأسلوبك واحتياجاتك.",
    "material_&_finish_selection": "اختيار المواد والتشطيبات",
    "material_&_finish_selection_desc": "اختيار المواد والألوان والتشطيبات للأرضيات والجدران والأسطح.",
    "lighting_design": "تصميم الإضاءة",
    "lighting_design_desc": "إنشاء خطط إضاءة تعزز الأجواء والوظائف.",
    "acoustical_design": "التصميم الصوتي",
    "acoustical_design_desc": "التخطيط لجودة الصوت المثلى والتحكم في الضوضاء في مساحاتك.",
    
    // Design Home third-level items - Landscape Architect
    "site_analysis_&_master_planning": "تحليل الموقع والتخطيط الرئيسي",
    "site_analysis_&_master_planning_desc": "تحليل وتخطيط شامل لكامل ممتلكاتك الخارجية.",
    "planting_design": "تصميم الزراعة",
    "planting_design_desc": "اختيار وترتيب النباتات للجمال والوظيفة والاستدامة.",
    "hardscape_design": "تصميم المناظر الصلبة",
    "hardscape_design_desc": "تصميم الباحات والممرات والجدران الاستنادية وغيرها من العناصر الهيكلية.",
    "irrigation_&_drainage_systems": "أنظمة الري والتصريف",
    "irrigation_&_drainage_systems_desc": "تخطيط أنظمة فعالة لإدارة المياه لمناظرك الطبيعية.",
    "sustainable_landscape_design": "تصميم المناظر الطبيعية المستدامة",
    "sustainable_landscape_design_desc": "إنشاء مساحات خارجية مسؤولة بيئيًا وقليلة الصيانة.",
    
    // Design Home third-level items - Sustainability Consultant
    "leed_certification_consulting": "استشارات شهادة LEED",
    "leed_certification_consulting_desc": "إرشادات للحصول على شهادة المباني الخضراء المعترف بها.",
    "renewable_energy_integration": "دمج الطاقة المتجددة",
    "renewable_energy_integration_desc": "دمج أنظمة الطاقة الشمسية أو الرياح أو الحرارية الأرضية في منزلك.",
    "building_envelope_optimization": "تحسين غلاف المبنى",
    "building_envelope_optimization_desc": "تحسين العزل وسد الهواء لكفاءة أكبر في استخدام الطاقة.",
    "energy_modeling_&_simulations": "نمذجة الطاقة والمحاكاة",
    "energy_modeling_&_simulations_desc": "تحليل الكمبيوتر للتنبؤ بأداء الطاقة في منزلك وتحسينه.",
    "green_materials_&_construction_practices": "المواد الخضراء وممارسات البناء",
    "green_materials_&_construction_practices_desc": "اختيار المواد المستدامة وغير السامة وطرق البناء.",
    "back_to_design": "العودة إلى التصميم",
    "back_to_categories": "العودة إلى الفئات",
    
    // Professional finder
    "professional_finder": "الباحث عن المحترفين",
    "professional_directory": "دليل المحترفين",
    "are_you_professional": "هل أنت مقدم خدمة محترف؟",
    "professional_question_desc": "يرجى تحديد ما إذا كنت تبحث عن مقدمي خدمات أو أنك محترف يقدم الخدمات",
    "want_to_be_listed": "هل تريد أن تظهر ضمن محترفي مجالك؟",
    "get_discovered": "اجعل أصحاب المنازل يكتشفونك عند البحث عن",
    "professionals": "المحترفين",
    "find_professionals": "البحث عن محترفين",
    "premium_listings": "تتضمن القوائم المميزة موضع أولوية وخيارات اتصال مباشرة.",
    "professional_listing_price": "قائمة المحترفين - 29.77 دولارًا شهريًا",
    "free_trial_info": "ابدأ بفترة تجريبية مجانية لمدة 60 يومًا! لا توجد رسوم حتى انتهاء الفترة التجريبية.",
    "want_to_be_listed_yes": "أريد أن أكون مدرجًا في الدليل",
    "for": "لـ",
    "want_to_browse": "أريد فقط تصفح الدليل",
    
    // Architect page
    "architect": "مهندس معماري",
    "architect_description": "مهندسون معماريون محترفون لتصميم وتخطيط مشروع منزلك",
    // Build Home page
    "search_services_placeholder": "ابحث عن الخدمات (مثال: 'كهر' للكهرباء، 'سبا' للسباكة)",
    "view_services": "عرض الخدمات",
    "view_options": "عرض الخيارات",
    "learn_more": "اعرف المزيد",
    "coming_soon": "قريباً! نحن نعمل على معلومات مفصلة لهذه الفئة.",
    
    // Category names with descriptions
    "construction_building": "البناء والتشييد",
    "construction_building_desc": "خدمات البناء الشاملة لمشروع بناء منزلك.",
    "mep": "الميكانيكا والكهرباء والسباكة",
    "mep_desc": "أنظمة الميكانيكا والكهرباء والسباكة الأساسية لمنزل وظيفي ومريح.",
    "utilities_infrastructure": "المرافق والبنية التحتية",
    "utilities_infrastructure_desc": "ربط المرافق الأساسية بمنزلك للحياة اليومية.",
    "renewable_solar": "الطاقة المتجددة والشمسية",
    "renewable_solar_desc": "حلول الطاقة المستدامة للمنازل الحديثة والفعالة.",
    "energy_building_systems": "أنظمة الطاقة والبناء",
    "energy_building_systems_desc": "أنظمة بناء ذكية وفعالة للحياة العصرية.",
    "environmental_compliance": "البيئة والامتثال",
    "environmental_compliance_desc": "خدمات الامتثال البيئي وتقييم الأثر البيئي.",
    "additional_expertise": "خبرات إضافية",
    "additional_expertise_desc": "خدمات متخصصة إضافية لبناء المنازل واحتياجات التجديد.",
    
    // Subcategories
    "subcategory_general_contractors": "مقاولون عامون",
    "subcategory_general_contractors_desc": "احصل على مقاولين للمنازل السكنية والبناء المخصص والتجديدات الشاملة.",
    "subcategory_structural_engineers": "مهندسون إنشائيون",
    "subcategory_structural_engineers_desc": "خبراء في تحليل وتصميم الهياكل الآمنة للمنازل السكنية والتجارية.",
    "subcategory_foundation_specialists": "متخصصون في الأساسات",
    "subcategory_foundation_specialists_desc": "خبراء في بناء وإصلاح أساسات خرسانية متينة وطوابق سفلية.",
    "subcategory_framing_contractors": "مقاولو الهيكلة",
    "subcategory_framing_contractors_desc": "متخصصون في هياكل الأخشاب والفولاذ لجدران وأسقف وأرضيات منزلك.",
    "subcategory_roofing_specialists": "متخصصون في الأسقف",
    "subcategory_roofing_specialists_desc": "تركيب وإصلاح الأسقف بمختلف المواد للحماية المثالية من العوامل الجوية.",
    "subcategory_siding_contractors": "مقاولو الكسوة",
    "subcategory_siding_contractors_desc": "تركيب كسوة جذابة ومتينة للمنازل لتحسين المظهر والحماية.",
    "subcategory_window_contractors": "مقاولو النوافذ",
    "subcategory_window_contractors_desc": "تركيب نوافذ عالية الكفاءة ومتينة وجميلة تعزز مظهر منزلك.",
    "subcategory_masonry_contractors": "مقاولو البناء بالطوب",
    "subcategory_masonry_contractors_desc": "متخصصون في البناء بالطوب والحجر لواجهات المنازل والمواقد والأسوار.",
    
    // Additional subcategories from console logs
    "subcategory_welding_specialist": "اللحام وتصنيع المعادن",
    "subcategory_welding_specialist_desc": "متخصصون في أعمال اللحام وتصنيع الهياكل المعدنية المخصصة.",
    "subcategory_roofing_and_cladding": "التسقيف والكسوة",
    "subcategory_roofing_and_cladding_desc": "تركيب وإصلاح الأسقف والكسوة الخارجية للمباني بمختلف المواد.",
    "subcategory_window_and_door_installer": "تركيب النوافذ والأبواب",
    "subcategory_window_and_door_installer_desc": "تركيب نوافذ وأبواب عالية الجودة وموفرة للطاقة.",
    "subcategory_insulation_contractor": "مقاول العزل",
    "subcategory_insulation_contractor_desc": "تركيب مواد العزل الحراري والصوتي للمباني.",
    "subcategory_drywall_and_plasterer": "الجبس والتجصيص",
    "subcategory_drywall_and_plasterer_desc": "تركيب وتشطيب ألواح الجبس والأسطح المجصصة.",
    "subcategory_flooring_specialist": "متخصص الأرضيات",
    "subcategory_flooring_specialist_desc": "تركيب أنواع متعددة من الأرضيات مثل الخشب والبلاط والفينيل.",
    "subcategory_painter_and_sprayer": "الدهان والرش",
    "subcategory_painter_and_sprayer_desc": "خدمات دهان وطلاء عالية الجودة للأسطح الداخلية والخارجية.",
    "subcategory_cabinetmaker_and_millworker": "صناعة الخزائن والأعمال الخشبية",
    "subcategory_cabinetmaker_and_millworker_desc": "تصميم وتصنيع وتركيب الخزائن والأعمال الخشبية المخصصة.",
    "subcategory_pool_builder": "بناء المسابح",
    "subcategory_pool_builder_desc": "تصميم وبناء وتركيب المسابح الداخلية والخارجية.",
    "subcategory_gardening_and_landscaping_expert": "خبير البستنة وتنسيق الحدائق",
    "subcategory_gardening_and_landscaping_expert_desc": "تصميم وتنفيذ مشاريع المناظر الطبيعية والحدائق.",
    
    // MEP subcategories
    "subcategory_hvac_technician": "فني التدفئة والتهوية وتكييف الهواء",
    "subcategory_hvac_technician_desc": "تركيب وصيانة أنظمة التدفئة والتهوية وتكييف الهواء.",
    "subcategory_electrician": "كهربائي",
    "subcategory_electrician_desc": "أعمال كهربائية متخصصة لأنظمة الطاقة الآمنة والفعالة.",
    "subcategory_plumber": "سباك",
    "subcategory_plumber_desc": "تركيب وإصلاح أنظمة إمدادات المياه والصرف.",
    
    // Third level items
    "residential_general_contractors": "مقاولون عامون للمساكن",
    "residential_general_contractors_desc": "محترفون متخصصون في بناء وتجديد المنازل السكنية.",
    "commercial_general_contractors": "مقاولون عامون للمباني التجارية",
    "commercial_general_contractors_desc": "خبراء في بناء وتجديد المساحات التجارية والمباني متعددة الوحدات.",
    "custom_home_builders": "بناة المنازل المخصصة",
    "custom_home_builders_desc": "متخصصون في إنشاء منازل مخصصة تعكس أسلوبك الشخصي واحتياجاتك.",
    "renovation_specialists": "متخصصو التجديد",
    "renovation_specialists_desc": "خبراء في تحويل المساحات الحالية وتحديثها وإعادة تصميمها.",
    "engineering_consultants": "استشاريون هندسيون",
    "engineering_consultants_desc": "استشاريون محترفون يقدمون خبرات هندسية وإرشادات للمشاريع المعقدة.",
    "additional_structural_analysis": "تحليل إنشائي",
    "additional_structural_analysis_desc": "تقييم شامل لسلامة وقوة هياكل المباني وعناصرها.",
    "load_calculations": "حسابات الأحمال",
    "load_calculations_desc": "تحديد دقيق للأحمال الهيكلية والتصميم المناسب لتحملها.",
    "seismic_design": "تصميم مقاوم للزلازل",
    "seismic_design_desc": "تصميم هياكل قادرة على تحمل القوى الزلزالية والحد من الأضرار.",
    "concrete_foundations": "أساسات خرسانية",
    "concrete_foundations_desc": "بناء أساسات خرسانية متينة لدعم منزلك بشكل آمن.",
    "basement_construction": "بناء الطوابق السفلية",
    "basement_construction_desc": "إنشاء طوابق سفلية آمنة ومانعة لتسرب المياه لمساحات معيشية إضافية.",
    "foundation_repair": "إصلاح الأساسات",
    "foundation_repair_desc": "حلول متخصصة لإصلاح تشققات وهبوط وأضرار أساسات المنازل.",
    "underpinning_services": "خدمات التدعيم",
    "underpinning_services_desc": "تقوية أساسات المنازل الحالية لتحسين الاستقرار الهيكلي.",
    "timber_framing": "هيكلة الأخشاب",
    "timber_framing_desc": "بناء هياكل خشبية متينة وجمالية للمنازل السكنية.",
    "steel_framing": "هيكلة الفولاذ",
    "steel_framing_desc": "هياكل فولاذية قوية مقاومة للحريق والعفن لمنازل أكثر متانة.",
    "wall_framing": "هيكلة الجدران",
    "wall_framing_desc": "بناء هياكل جدران دقيقة لدعم التشطيبات الداخلية والخارجية.",
    "ceiling_and_floor_framing": "هيكلة السقف والأرضيات",
    "ceiling_and_floor_framing_desc": "إنشاء هياكل أسقف وأرضيات متينة لضمان السلامة والاستقرار.",
    
    // Service-related terms
    "rating": "تقييم",
    "reviews": "المراجعات",
    "price_range": "نطاق السعر",
    "contact_info": "معلومات الاتصال",
    "profile": "الملف الشخصي",
    "availability": "التوفر",
    "services_offered": "الخدمات المقدمة",
    
    // Renewable & Solar subcategories
    "subcategory_solar_installer": "فني تركيب الطاقة الشمسية",
    "subcategory_solar_installer_desc": "تركيب احترافي لألواح الطاقة الشمسية والمعدات ذات الصلة.",
    "subcategory_solar_designer": "مصمم أنظمة الطاقة الشمسية",
    "subcategory_solar_designer_desc": "تصميم خبير لأنظمة الطاقة الشمسية المثلى لمنزلك.",
    
    // Energy & Building Systems subcategories
    "subcategory_home_automation": "متخصص أتمتة المنزل",
    "subcategory_home_automation_desc": "دمج تكنولوجيا المنزل الذكي للراحة والكفاءة.",
    "smart_home_control": "التحكم في المنزل الذكي",
    "smart_home_control_desc": "أجهزة التحكم المركزية لنظام منزلك الذكي.",
    "security_automation": "أتمتة الأمان",
    "security_automation_desc": "أقفال رقمية وقارئات بيومترية وأنظمة مراقبة أمنية.",
    "smart_lighting": "إضاءة ذكية",
    "smart_lighting_desc": "أنظمة إضاءة آلية للكفاءة والأجواء.",
    "climate_control": "التحكم في المناخ",
    "climate_control_desc": "منظمات حرارة ذكية وأنظمة أتمتة التدفئة والتهوية وتكييف الهواء.",
    "entertainment_systems": "أنظمة الترفيه",
    "entertainment_systems_desc": "حلول أتمتة الصوت والترفيه لكامل المنزل.",
    
    // Environmental & Compliance subcategories
    "subcategory_leed_consultant": "استشاري شهادة LEED",
    "subcategory_leed_consultant_desc": "إرشادات للحصول على شهادات البناء المستدام.",
    "subcategory_environmental_assessor": "مقيم الأثر البيئي",
    "subcategory_environmental_assessor_desc": "تقييم الآثار البيئية لمشروع البناء الخاص بك.",
    
    // Utilities & Infrastructure subcategories
    "subcategory_utility_connection": "متخصص توصيل المرافق",
    "subcategory_utility_connection_desc": "مساعدة خبيرة في الاتصال بأنظمة المرافق البلدية.",
    "subcategory_septic_system": "خبير أنظمة الصرف الصحي",
    "subcategory_septic_system_desc": "تركيب وصيانة أنظمة الصرف الصحي للعقارات الريفية.",
    
    // Additional Expertise subcategories
    "subcategory_security_system_installer": "فني تركيب أنظمة الأمان",
    "subcategory_security_system_installer_desc": "حلول أمان منزلية شاملة لراحة بالك.",
    "subcategory_locksmith": "صانع المفاتيح",
    "subcategory_locksmith_desc": "تركيب وصيانة المفاتيح والأقفال وأجهزة الأمان الاحترافية.",
    "residential_locksmith": "صانع مفاتيح سكني",
    "residential_locksmith_desc": "أقفال المنازل وأنظمة الدخول بدون مفاتيح وأنظمة المفاتيح الرئيسية.",
    "commercial_locksmith": "صانع مفاتيح تجاري",
    "commercial_locksmith_desc": "أقفال أمان تجارية وأجهزة الذعر وأنظمة التحكم في الوصول.",
    "automotive_locksmith": "صانع مفاتيح السيارات",
    "automotive_locksmith_desc": "نسخ مفاتيح السيارات وإصلاح نظام التشغيل وبرمجة مفاتيح الإرسال.",
    "emergency_lockout_service": "خدمة طوارئ فتح الأقفال",
    "emergency_lockout_service_desc": "خدمة طوارئ على مدار الساعة لفتح أقفال المنازل والشركات والمركبات.",
    "safe_installation_repair": "تركيب وإصلاح الخزائن",
    "safe_installation_repair_desc": "تركيب وتغيير التركيبات وإصلاحات للخزائن المنزلية والمكتبية.",
    "subcategory_soundproofing_specialist": "متخصص عزل الصوت",
    "subcategory_soundproofing_specialist_desc": "إنشاء مساحات هادئة ومتوازنة صوتياً في منزلك.",
    "subcategory_accessibility_expert": "خبير إمكانية الوصول",
    "subcategory_accessibility_expert_desc": "جعل منزلك مريحاً ويمكن الوصول إليه للجميع.",
    "subcategory_pest_control": "مكافحة الآفات",
    "subcategory_pest_control_desc": "حماية منزلك من الآفات غير المرغوب فيها أثناء وبعد البناء.",
    "subcategory_waste_management": "منسق إدارة النفايات وإعادة التدوير",
    "subcategory_waste_management_desc": "التخلص المسؤول وإعادة تدوير مواد البناء.",
    "subcategory_metal_fabrication_specialist": "متخصص اللحام وتصنيع المعادن",
    "subcategory_metal_fabrication_specialist_desc": "تصنيع المعادن المخصصة والأعمال الحديدية الزخرفية وخدمات اللحام المتخصصة.",
    "artistic_metalwork": "أعمال المعادن الفنية",
    "artistic_metalwork_desc": "عناصر معدنية زخرفية مخصصة وأعمال معدنية فنية لميزات منزلية فريدة.",
    "specialty_metals": "المعادن المتخصصة",
    "specialty_metals_desc": "العمل مع الألمنيوم والفولاذ المقاوم للصدأ والنحاس والبرونز وغيرها من المعادن المتخصصة.",
    "metal_restoration": "ترميم المعادن",
    "metal_restoration_desc": "إصلاح وترميم الأعمال المعدنية والتركيبات التاريخية أو العتيقة.",
    "sheet_metal_fabrication": "تصنيع الألواح المعدنية",
    "sheet_metal_fabrication_desc": "أعمال الألواح المعدنية المخصصة للتدفئة والتهوية وتكييف الهواء والتسقيف والميزات المعمارية.",
    "architectural_metals": "المعادن المعمارية",
    "architectural_metals_desc": "ميزات معدنية متخصصة للتطبيقات المعمارية وعناصر التصميم.",
    
    // Build part - additional translations
    "carpentry": "النجارة",
    "carpentry_desc": "خدمات نجارة ماهرة للإطار الهيكلي والتفاصيل الخشبية.",
    "welding_&_metal_fabrication": "اللحام وتصنيع المعادن",
    "welding_&_metal_fabrication_desc": "لحام متخصص وتصنيع المعادن للعناصر الهيكلية والزخرفية.",
    "metal_work_&_welding_specialist": "متخصص أعمال المعادن واللحام",
    "metal_work_&_welding_specialist_desc": "تصنيع المعادن المخصصة، والأعمال الحديدية الزخرفية، وخدمات اللحام المتخصصة.",
    
    // Finance pages
    "mortgage": "الرهن العقاري",
    "insurance": "التأمين",
    "credit_repair": "إصلاح الائتمان",
    "financial_planning": "التخطيط المالي", 
    "real_estate_agents": "وكلاء العقارات",
    "loan_officers": "مسؤولي القروض",
    "find_finance_professionals": "ابحث عن محترفي التمويل والعقارات",
    "find_connect_finance_professionals": "ابحث وتواصل مع خبراء التمويل والعقارات لمساعدتك في رحلة امتلاك منزلك",
    "connect_with_category": "تواصل مع {category} الذين يمكنهم مساعدتك في تمويل منزلك أو شرائه أو بيعه",
    "search_finance_professionals": "ابحث عن محترفي التمويل والعقارات",
    "no_finance_professionals_found": "لم يتم العثور على محترفي تمويل وعقارات",
    "professional_types_count": "{count} نوع من المحترفين بما في ذلك {services}، والمزيد.",
    
    // Finance categories
    "credit_repair_debt_management": "إصلاح الائتمان وإدارة الديون",
    "mortgage_loan_professionals": "محترفو الرهن العقاري والقروض",
    "construction_finance_experts": "خبراء تمويل البناء",
    "home_improvement_financing": "تمويل تحسين المنزل",
    "equity_refinance_debt": "أسهم وإعادة تمويل وديون",
    "first_time_buyer_credit": "مشتري لأول مرة وائتمان",
    "real_estate_investment_experts": "خبراء الاستثمار العقاري",
    "real_estate_property_professionals": "محترفو العقارات والممتلكات",
    "financial_planning_tax_experts": "خبراء التخطيط المالي والضرائب",
    
    // Credit Repair Services
    "credit_repair_expert": "خبير إصلاح الائتمان",
    "credit_repair_expert_desc": "متخصصون مهنيون يساعدون على استعادة وتحسين درجة الائتمان الخاصة بك من خلال عمليات نزاع مشروعة واستراتيجيات إعادة بناء الائتمان.",
    "debt_management_counselor": "مستشار إدارة الديون",
    "debt_management_counselor_desc": "محترفون ماليون يقومون بإنشاء خطط مخصصة لمساعدتك في إدارة وتقليل ديونك من خلال وضع الميزانية والتوحيد والتفاوض.",
    "credit_score_analyst": "محلل درجة الائتمان",
    "credit_score_analyst_desc": "محترفون يحللون تقرير الائتمان الخاص بك لتحديد المشكلات وتطوير خطة مخصصة لتحسين درجة الائتمان الخاصة بك.",
    "credit_dispute_specialist": "متخصص في النزاعات الائتمانية",
    "credit_dispute_specialist_desc": "خبراء يساعدونك في الاعتراض على العناصر غير الدقيقة أو غير العادلة في تقرير الائتمان الخاص بك لتحسين درجة الائتمان الإجمالية.",
    "credit_rebuilding_advisor": "مستشار إعادة بناء الائتمان",
    "credit_rebuilding_advisor_desc": "محترفون يساعدونك على تطوير عادات ائتمانية صحية وتنفيذ استراتيجيات لإعادة بناء رصيدك الائتماني بعد ضائقة مالية.",
    
    // Mortgage Services
    "mortgage_broker": "وسيط الرهن العقاري",
    "mortgage_broker_desc": "محترفون خبراء يربطونك بأفضل معدلات وشروط الرهن العقاري لاحتياجاتك المحددة.",
    "loan_officer": "مسؤول القروض",
    "loan_officer_desc": "متخصصون ماليون يساعدونك في التنقل بين خيارات القروض المختلفة لشراء المنازل وإعادة التمويل.",
    "mortgage_banker": "مصرفي الرهن العقاري",
    "mortgage_banker_desc": "محترفون مصرفيون يمولون قروض الرهن العقاري مباشرة ويديرون عملية الإقراض بأكملها.",
    "fha_loan_specialist": "متخصص قروض FHA",
    "fha_loan_specialist_desc": "خبراء في القروض المدعومة من الحكومة المصممة لمشتري المنازل لأول مرة مع متطلبات دفع مقدم أقل.",
    "cash-out_refinance_specialist": "متخصص إعادة تمويل السحب النقدي",
    "cash-out_refinance_specialist_desc": "خبراء يساعدون أصحاب المنازل على استبدال الرهن العقاري بقرض أكبر للوصول إلى حقوق الملكية نقدًا.",
    "first-time_homebuyer_counselor": "مستشار مشتري المنزل لأول مرة",
    "first-time_homebuyer_counselor_desc": "محترفون يوجهون المشترين لأول مرة خلال عملية شراء المنزل بأكملها.",
    
    // Construction Finance 
    "construction_loan_specialist": "متخصص قروض البناء",
    "construction_loan_specialist_desc": "محترفون ماليون متخصصون في تأمين التمويل لمشاريع بناء المنازل الجديدة.",
    "building_project_financier": "ممول مشروع البناء",
    "building_project_financier_desc": "خبراء يساعدون في ترتيب حزم تمويل شاملة لمشاريع البناء الكبيرة.",
    "architectural_finance_consultant": "مستشار التمويل المعماري",
    "architectural_finance_consultant_desc": "متخصصون يربطون الشركات المعمارية بخيارات التمويل المناسبة للعملاء.",
    "contractor_finance_advisor": "مستشار تمويل المقاولين",
    "contractor_finance_advisor_desc": "محترفون ماليون يساعدون المقاولين في تأمين تمويل المشروع وإدارة جداول الدفع.",
    
    // Home Improvement
    "renovation_loan_specialist": "متخصص قروض التجديد",
    "renovation_loan_specialist_desc": "خبراء في تأمين خيارات التمويل خصيصًا لمشاريع تجديد المنازل وإعادة التشكيل.",
    "home_improvement_financial_advisor": "مستشار مالي لتحسين المنزل",
    "home_improvement_financial_advisor_desc": "محترفون يساعدون أصحاب المنازل في تخطيط وتمويل مشاريع تحسين ممتلكاتهم.",
    "heloc_specialist": "متخصص في خطوط ائتمان حقوق ملكية المنزل",
    "heloc_specialist_desc": "خبراء في خطوط ائتمان حقوق ملكية المنزل يساعدون أصحاب المنازل على الاستفادة من قيمة ممتلكاتهم للتجديدات.",
    "green_improvement_financier": "ممول التحسينات الخضراء",
    "green_improvement_financier_desc": "متخصصون في الحصول على قروض وحوافز لتحسينات المنزل الموفرة للطاقة.",
    
    // Equity & Refinance
    "refinance_specialist": "متخصص إعادة التمويل",
    "refinance_specialist_desc": "محترفون يساعدون أصحاب المنازل على استبدال الرهون العقارية الحالية بشروط أو أسعار أفضل.",
    "equity_release_consultant": "مستشار إطلاق حقوق الملكية",
    "equity_release_consultant_desc": "خبراء يساعدون أصحاب المنازل على الوصول إلى القيمة في ممتلكاتهم دون بيعها.",
    "debt_consolidation_advisor": "مستشار توحيد الديون",
    "debt_consolidation_advisor_desc": "محترفون ماليون يساعدون في دمج ديون متعددة في دفعة واحدة أكثر قابلية للإدارة.",
    "debt_settlement_negotiator": "مفاوض تسوية الديون",
    "debt_settlement_negotiator_desc": "متخصصون يتفاوضون مع الدائنين لتقليل المبلغ الإجمالي للديون المستحقة قبل تطوير خطة السداد.",
    
    // First Time Buyer
    "down_payment_assistance_specialist": "متخصص في المساعدة في الدفعة الأولى",
    "down_payment_assistance_specialist_desc": "خبراء في البرامج التي تقدم مساعدة مالية للمساعدة في تغطية الدفعة الأولى عند شراء منزل.",
    "first_time_credit_repair_expert": "خبير إصلاح الائتمان لأول مرة",
    "first_time_credit_repair_expert_desc": "متخصصون مهنيون يساعدون على استعادة وتحسين درجة الائتمان الخاصة بك من خلال عمليات نزاع مشروعة واستراتيجيات إعادة بناء الائتمان.",
    "affordable_housing_consultant": "مستشار الإسكان الميسور التكلفة",
    "affordable_housing_consultant_desc": "متخصصون يربطون المشترين بخيارات الإسكان الميسورة التكلفة وبرامج التمويل المرتبطة بها.",
    
    // Real Estate Investment
    "investment_property_specialist": "متخصص في عقارات الاستثمار",
    "investment_property_specialist_desc": "مستشارون ماليون يركزون على مساعدة العملاء في شراء وتمويل العقارات المدرة للدخل.",
    "reit_advisor": "مستشار صناديق الاستثمار العقاري",
    "reit_advisor_desc": "محترفون متخصصون في صناديق الاستثمار العقاري وغيرها من الأوراق المالية المستندة إلى الممتلكات.",
    "property_portfolio_manager": "مدير محفظة العقارات",
    "property_portfolio_manager_desc": "خبراء يديرون عقارات استثمارية متعددة واعتباراتها المالية المرتبطة بها.",
    "real_estate_investment_consultant": "مستشار الاستثمار العقاري",
    "real_estate_investment_consultant_desc": "مستشارون استراتيجيون للأفراد الذين يتطلعون إلى بناء الثروة من خلال استثمارات العقارات.",
    
    // Real Estate Property
    "real_estate_agent": "وكيل عقارات",
    "real_estate_agent_desc": "محترفون مرخصون يساعدون المشترين والبائعين في التنقل في سوق العقارات.",
    "property_appraiser": "مقيم العقارات",
    "property_appraiser_desc": "خبراء يحددون القيمة السوقية للعقارات للتمويل أو البيع أو أغراض الضرائب.",
    "escrow_officer": "مسؤول الضمان",
    "escrow_officer_desc": "محترفون يديرون نقل الأموال والمستندات أثناء معاملات العقارات.",
    "real_estate_attorney": "محامي العقارات",
    "real_estate_attorney_desc": "محترفون قانونيون متخصصون في معاملات الممتلكات والعقود وقانون العقارات.",
    
    // Financial Planning
    "financial_planner": "مخطط مالي",
    "financial_planner_desc": "مستشارون ماليون شاملون يساعدون في وضع الميزانية والاستثمارات والتخطيط طويل المدى لملكية المنزل.",
    "property_tax_consultant": "مستشار ضريبة الممتلكات",
    "property_tax_consultant_desc": "متخصصون يساعدون أصحاب المنازل في إدارة التزامات ضريبة الممتلكات الخاصة بهم وتقليلها المحتمل.",
    "tax_credit_specialist": "متخصص في الائتمان الضريبي",
    "tax_credit_specialist_desc": "متخصصون مهنيون يساعدون على استعادة وتحسين درجة الائتمان الخاصة بك من خلال عمليات نزاع مشروعة واستراتيجيات إعادة بناء الائتمان.",
    "estate_planning_attorney": "محامي تخطيط العقارات",
    "estate_planning_attorney_desc": "خبراء قانونيون يساعدون أصحاب المنازل في التخطيط لمستقبل ممتلكاتهم وأصولهم."
  },
  zh: {
    "back": "返回",
    "category_not_found": "未找到类别",
    "design_home": "家居设计",
    "build_home": "房屋建造",
    "finance_real_estate": "财务与房地产",
    "design": "设计",
    "build": "建造",
    "finance": "财务",
    "real_estate_short": "房地产",
    "looking_for_professionals": "我正在寻找专业人士",
    "i_am_professional": "我是专业人士",
    "home": "首页",
    "support": "支持",
    "services": "服务",
    "contact": "联系",
    "login": "登录",
    "my_profile": "我的档案",
    "my_account": "我的账户",
    "next": "下一步",
    "previous": "上一步",
    "submit": "提交",
    "cancel": "取消",
    "logout": "退出登录",
    "register": "注册",
    "email": "电子邮件",
    "password": "密码",
    "construction_building": "建筑与施工",
    "mep": "机械、电气、管道",
    "utilities_infrastructure": "公用设施与基础设施",
    "renewable_solar": "可再生能源与太阳能",
    "energy_building_systems": "能源与建筑系统",
    "environmental_compliance": "环境与合规",
    "additional_expertise": "其他专业知识"
  },
  hi: {
    "back": "वापस",
    "category_not_found": "श्रेणी नहीं मिली",
    "design_home": "घर का डिज़ाइन",
    "build_home": "घर का निर्माण",
    "finance_real_estate": "वित्त और रियल एस्टेट",
    "design": "डिज़ाइन",
    "build": "निर्माण",
    "finance": "वित्त",
    "real_estate_short": "रियल एस्टेट",
    "looking_for_professionals": "मैं पेशेवरों की तलाश कर रहा हूँ",
    "i_am_professional": "मैं एक पेशेवर हूँ",
    "home": "मुख्य पृष्ठ",
    "support": "सहायता",
    "services": "सेवाएँ",
    "contact": "संपर्क",
    "login": "लॉगिन",
    "my_profile": "मेरी प्रोफ़ाइल",
    "my_account": "मेरा खाता",
    "next": "अगला",
    "previous": "पिछला",
    "submit": "जमा करें",
    "cancel": "रद्द करें",
    "logout": "लॉगआउट",
    "register": "पंजीकरण",
    "email": "ईमेल",
    "password": "पासवर्ड",
    "construction_building": "निर्माण और भवन",
    "mep": "मैकेनिकल, इलेक्ट्रिकल, प्लंबिंग",
    "utilities_infrastructure": "उपयोगिताएँ और बुनियादी ढांचा",
    "renewable_solar": "नवीकरणीय और सौर ऊर्जा",
    "energy_building_systems": "ऊर्जा और भवन प्रणालियाँ",
    "environmental_compliance": "पर्यावरण और अनुपालन",
    "additional_expertise": "अतिरिक्त विशेषज्ञता"
  },
  tl: {
    "back": "Bumalik",
    "category_not_found": "Hindi Nahanap ang Kategorya",
    "design_home": "Disenyo ng Bahay",
    "build_home": "Pagbuo ng Bahay",
    "finance_real_estate": "Pananalapi at Real Estate",
    "design": "Disenyo",
    "build": "Pagbuo",
    "finance": "Pananalapi",
    "real_estate_short": "Real estate",
    "looking_for_professionals": "Naghahanap ako ng mga propesyonal",
    "i_am_professional": "Ako ay isang propesyonal",
    "home": "Tahanan",
    "support": "Suporta",
    "services": "Mga Serbisyo",
    "contact": "Kontak",
    "login": "Mag-login",
    "my_profile": "Aking Profile",
    "my_account": "Aking Account",
    "next": "Susunod",
    "previous": "Nakaraan",
    "submit": "Isumite",
    "cancel": "Kanselahin",
    "logout": "Mag-logout",
    "register": "Magrehistro",
    "email": "Email",
    "password": "Password",
    "construction_building": "Konstruksyon at Gusali",
    "mep": "MEP (Mekanikal, Elektrikal, Plumbing)",
    "utilities_infrastructure": "Mga Utility at Imprastraktura",
    "renewable_solar": "Renewable at Solar",
    "energy_building_systems": "Enerhiya at Mga Sistema ng Gusali",
    "environmental_compliance": "Kapaligiran at Pagsunod",
    "additional_expertise": "Karagdagang Kadalubhasaan"
  },
  ko: {
    "back": "뒤로",
    "category_not_found": "카테고리를 찾을 수 없음",
    "design_home": "홈 디자인",
    "build_home": "홈 건설",
    "finance_real_estate": "금융 및 부동산",
    "design": "디자인",
    "build": "건설",
    "finance": "금융",
    "real_estate_short": "부동산",
    "looking_for_professionals": "전문가를 찾고 있습니다",
    "i_am_professional": "저는 전문가입니다",
    "home": "홈",
    "support": "지원",
    "services": "서비스",
    "contact": "연락처",
    "login": "로그인",
    "my_profile": "내 프로필",
    "my_account": "내 계정",
    "next": "다음",
    "previous": "이전",
    "submit": "제출",
    "cancel": "취소",
    "logout": "로그아웃",
    "register": "등록",
    "email": "이메일",
    "password": "비밀번호",
    "construction_building": "건설 및 건축",
    "mep": "MEP (기계, 전기, 배관)",
    "utilities_infrastructure": "유틸리티 및 인프라",
    "renewable_solar": "재생 에너지 및 태양광",
    "energy_building_systems": "에너지 및 건물 시스템",
    "environmental_compliance": "환경 및 규정 준수",
    "additional_expertise": "추가 전문 지식"
  }
};