platform :ios, '14.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  pod 'Capacitor', '~> 5.0'
  pod 'CapacitorCordova', '~> 5.0'
  pod 'CapacitorApp', '~> 5.0'
  pod 'CapacitorBrowser', '~> 5.0'
  pod 'CapacitorDevice', '~> 5.0'
  pod 'CapacitorNetwork', '~> 5.0'
  pod 'CapacitorPreferences', '~> 5.0'
  pod 'CapacitorSplashScreen', '~> 5.0'
  pod 'CapacitorStatusBar', '~> 5.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
