name: iOS Build Streamlined

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: List available simulators
      run: xcrun simctl list devices available
      
    - name: Build for simulator
      run: |
        cd ios/App
        xcodebuild clean build \
          -project App.xcodeproj \
          -scheme App \
          -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          DEVELOPMENT_TEAM="" \
          PROVISIONING_PROFILE=""
          
    - name: Create unsigned archive
      run: |
        cd ios/App
        mkdir -p build
        xcodebuild archive \
          -project App.xcodeproj \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath build/App.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM="" \
          PROVISIONING_PROFILE="" \
          -allowProvisioningUpdates
          
    - name: Verify archive
      run: |
        ls -la ios/App/build/
        if [ -d "ios/App/build/App.xcarchive" ]; then
          echo "Archive created successfully"
          ls -la ios/App/build/App.xcarchive/
        else
          echo "Archive creation failed"
          exit 1
        fi
        
    - name: Package for download
      run: |
        cd ios/App/build
        zip -r App.xcarchive.zip App.xcarchive
        
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: usa-home-ios-app
        path: ios/App/build/App.xcarchive.zip
        retention-days: 30
